'use strict';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const money = value => new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value);
const products = {
  solar: { name: 'Solar Drift', number: '001', family: 'fresh', descriptor: 'THE GOLDEN ONE', tagline: 'Sun on skin. Now bottled.', mood: 'a little sunshine<br>goes a long way.', notes: 'Bergamot · Neroli · Soft musk', top: 'Bergamot, mandarin', heart: 'Neroli, orange blossom', base: 'Soft musk, blonde woods', description: 'The windows are open. There is nowhere you need to be. Bright citrus drifts into a heart of orange blossom, settling into the soft warmth of skin. A little golden hour, whenever you need it.', keywords: 'sun sunshine sunny bright luminous citrus floral golden fresh summer morning', sizes: { '50': 89, '100': 139 } },
  after: { name: 'After Hours', number: '002', family: 'woody', descriptor: 'THE UNEXPECTED ONE', tagline: 'Stay a little longer.', mood: 'one more<br>last night.', notes: 'Black tea · Iris · Sandalwood', top: 'Black tea, pink pepper', heart: 'Iris, violet leaf', base: 'Sandalwood, amber', description: 'The city is quieter now. The conversation is getting better. Smoky tea and a spark of pepper unfold into powdery iris and warm, textured woods. For the nights that become stories.', keywords: 'night evening deep dark warm woody amber smoky tea mysterious', sizes: { '50': 89, '100': 139 } },
  soft: { name: 'Soft Static', number: '003', family: 'soft', descriptor: 'THE QUIET ONE', tagline: 'Close to skin. Closer to you.', mood: 'the art of<br>doing nothing.', notes: 'Pear · Ambrette · White woods', top: 'Pear, bergamot', heart: 'Ambrette, white iris', base: 'White woods, skin musk', description: 'Fresh sheets. A slow Sunday. The lovely luxury of having nothing planned. Crisp pear melts into ambrette and whisper-soft woods. An intimate fragrance that feels like your favorite version of home.', keywords: 'quiet clean soft intimate skin delicate gentle cozy musk pear sunday', sizes: { '50': 89, '100': 139 } },
  discovery: { name: 'The Discovery Set', number: '000', family: 'all', descriptor: 'YOUR FIRST CHAPTER', notes: 'Solar Drift · After Hours · Soft Static', keywords: 'sample mini trial travel gift set discovery all', sizes: { set: 24 } }
};
const sizeText = size => size === 'set' ? '3 × 2 ml' : `${size} ml`;
function readStored(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function persist(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* The store remains usable with storage disabled. */ } }
const rawCart = readStored('oreyn-cart-v2', []);
let cart = Array.isArray(rawCart) ? rawCart.filter(item => item && typeof item.id === 'string' && Object.hasOwn(products, item.id) && typeof item.size === 'string' && Object.hasOwn(products[item.id].sizes, item.size) && Number.isInteger(item.quantity) && item.quantity > 0 && item.quantity <= 99).map(({ id, size, quantity }) => ({ id, size, quantity })) : [];
// Preserve bags created in the original site.
if (!cart.length && localStorageAvailable() && localStorage.getItem('oreyn-cart-v2') === null) {
  const previous = readStored('oreyn-bag', {});
  if (previous && typeof previous === 'object') Object.entries(products).forEach(([id, product]) => { if (Number.isInteger(previous[product.name]) && previous[product.name] > 0 && previous[product.name] <= 99) cart.push({ id, size: '50', quantity: previous[product.name] }); });
}
function localStorageAvailable() { try { return Boolean(window.localStorage); } catch { return false; } }
const savedRaw = readStored('oreyn-saved', []);
let saved = new Set(Array.isArray(savedRaw) ? savedRaw.filter(id => typeof id === 'string' && Object.hasOwn(products, id) && id !== 'discovery') : []);
let filter = 'all', heroId = 'solar', detailId = 'solar', detailSize = '50', giftWrap = false;
let toastTimer, lastModalTrigger;
const heart = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/></svg>';
function bottleMarkup(id, size = '50') { const p = products[id]; return `<div class="mini-bottle" aria-hidden="true"><div class="mini-cap"></div><div class="mini-body"><b>oreyn<sup>®</sup></b><span>${p.name.toUpperCase()}</span><small class="mini-volume">EAU DE PARFUM / ${size} ML</small></div></div>`; }
function notify(message, showBag = false) {
  const el = $('#toast'); el.replaceChildren();
  const text = document.createElement('span'); text.textContent = message; el.append(text);
  if (showBag) { const button = document.createElement('button'); button.textContent = 'View bag ↗'; button.setAttribute('data-view-bag', ''); el.append(button); }
  el.classList.add('visible'); clearTimeout(toastTimer);
  toastTimer = setTimeout(() => { if (!el.contains(document.activeElement)) el.classList.remove('visible'); }, showBag ? 6000 : 3200);
}
function openModal(id) {
  if (!$('dialog[open]')) lastModalTrigger = document.activeElement;
  $$('dialog[open]').forEach(dialog => dialog.close());
  closeMenu();
  const dialog = $(id); dialog.showModal(); dialog.scrollTop = 0;
  window.oreynModalOpen = true; window.dispatchEvent(new Event('oreyn-motion'));
}
function closeModal(dialog) { dialog.close(); if (dialog.id === 'product-dialog' && location.hash.startsWith('#scent/')) history.replaceState(null, '', '#collection'); if (lastModalTrigger?.isConnected) lastModalTrigger.focus({ preventScroll: true }); }
$$('dialog').forEach(dialog => {
  dialog.addEventListener('close', () => { window.oreynModalOpen = Boolean($('dialog[open]')); window.dispatchEvent(new Event('oreyn-motion')); });
  dialog.addEventListener('click', event => { if (event.target === dialog) { const b = dialog.getBoundingClientRect(); if (event.clientX < b.left || event.clientX > b.right || event.clientY < b.top || event.clientY > b.bottom) closeModal(dialog); } });
  dialog.addEventListener('cancel', event => { event.preventDefault(); closeModal(dialog); });
});
function saveButton(id) { return `<button class="save-button" data-save="${id}" aria-label="${saved.has(id) ? 'Unsave' : 'Save'} ${products[id].name}" aria-pressed="${saved.has(id)}">${heart}</button>`; }
function renderProducts() {
  const matches = Object.entries(products).filter(([id, p]) => id !== 'discovery' && (filter === 'all' || filter === 'saved' && saved.has(id) || p.family === filter));
  $('#product-grid').innerHTML = matches.map(([id, p]) => `<article class="product-card"><div class="product-art ${id}"><span class="art-index">${p.number} / ${p.descriptor}</span>${saveButton(id)}<button class="product-view" data-product="${id}" aria-label="Explore ${p.name}">${bottleMarkup(id)}</button><span class="art-mood">${p.mood}</span></div><div class="product-info"><div><h3><button data-product="${id}">${p.name}</button></h3><span>${money(p.sizes['50'])}</span></div><p>${p.notes}</p><div class="product-info-bottom"><span>EAU DE PARFUM / 50 ML</span><button data-product="${id}">View details ↗</button></div><button class="card-add" data-add="${id}" data-size="50" aria-label="Add ${p.name}, 50 ml, to bag">Add to bag · ${money(p.sizes['50'])}<span aria-hidden="true">+</span></button></div></article>`).join('') || '<div class="empty-state"><h3>A feeling worth keeping.</h3><p>Tap a heart on any scent to keep it here.</p><button class="pill dark" data-filter="all">Explore the collection <span>↗</span></button></div>';
  $('#collection-count').textContent = `${matches.length} fragrance${matches.length === 1 ? '' : 's'}`;
  $('#saved-count').textContent = saved.size;
  $$('.filters [data-filter]').forEach(button => { const active = button.dataset.filter === filter; button.classList.toggle('active', active); button.setAttribute('aria-pressed', active); });
}
function toggleSave(id) { const gridFocused = Boolean(document.activeElement?.closest('#product-grid')); saved.has(id) ? saved.delete(id) : saved.add(id); persist('oreyn-saved', [...saved]); renderProducts(); $$(`[data-save="${id}"]`).forEach(button => { button.setAttribute('aria-pressed', saved.has(id)); button.setAttribute('aria-label', `${saved.has(id) ? 'Unsave' : 'Save'} ${products[id].name}`); }); if (gridFocused) ($(`#product-grid [data-save="${id}"]`) || $(`.filters [data-filter="${filter}"]`))?.focus({ preventScroll: true }); notify(saved.has(id) ? `${products[id].name} saved to your collection` : `${products[id].name} removed from saved scents`); }
function openProduct(id, updateUrl = true) {
  if (!products[id] || id === 'discovery') return;
  detailId = id; detailSize = '50'; const p = products[id];
  $('#product-detail').innerHTML = `<div class="product-detail-grid"><div class="detail-art ${id}"><span class="eyebrow">${p.number} / ${p.descriptor}</span>${bottleMarkup(id)}<span class="art-mood">${p.mood}</span></div><div class="detail-content"><span class="eyebrow">EAU DE PARFUM / A SLICE OF LIFE</span><h2>${p.name}</h2><p class="detail-tagline">${p.tagline}</p><p class="detail-description">${p.description}</p><div class="note-pyramid"><div class="note-row"><span>OPENING</span>${p.top}</div><div class="note-row"><span>HEART</span>${p.heart}</div><div class="note-row"><span>LINGERING</span>${p.base}</div></div><span class="size-label">CHOOSE YOUR SIZE</span><div class="size-options" aria-label="Bottle size">${Object.entries(p.sizes).map(([size, price]) => `<button data-detail-size="${size}" class="${size === detailSize ? 'active' : ''}" aria-pressed="${size === detailSize}">${sizeText(size)} · ${money(price)}</button>`).join('')}</div><div class="detail-actions"><button class="pill dark" id="detail-add" data-add="${id}" data-size="50">Add to bag — ${money(p.sizes['50'])}<span>↗</span></button>${saveButton(id)}</div><button class="text-link detail-view-bag full-width" id="detail-view-bag" data-view-bag hidden>View your bag <span>↗</span></button><div class="detail-bottom"><span>A scent without labels. For everyone.</span><button data-share="${id}">Copy scent link ↗</button></div><button class="text-link" data-discovery-link style="margin-top:20px">Not quite sure? Try the discovery set ↗</button></div></div>`;
  $('#product-dialog').setAttribute('aria-label', `${p.name} fragrance details`);
  openModal('#product-dialog'); if (updateUrl) history.replaceState(null, '', `#scent/${id}`);
}
function cartTotals() { const subtotal = cart.reduce((sum, item) => sum + products[item.id].sizes[item.size] * item.quantity, 0); const wrapping = giftWrap && cart.length ? 5 : 0; const shipping = subtotal === 0 || subtotal >= 120 ? 0 : 6; return { subtotal, wrapping, shipping, total: subtotal + wrapping + shipping }; }
function addToCart(id, size) {
  if (!products[id] || !Object.hasOwn(products[id].sizes, size)) return;
  const item = cart.find(item => item.id === id && item.size === size);
  if (item?.quantity === 99) { notify('Maximum 99 of each size per bag.'); return; }
  item ? item.quantity++ : cart.push({ id, size, quantity: 1 }); renderBag(); notify(`${products[id].name} added to your bag`, true); const bagLink = $('#detail-view-bag'); if (bagLink) bagLink.hidden = false;
  const button = $('#detail-add'); if (button && $('#product-dialog').open) { button.innerHTML = 'Added to your bag <span>✓</span>'; setTimeout(() => { if (button.isConnected) button.innerHTML = `Add to bag — ${money(products[detailId].sizes[detailSize])}<span>↗</span>`; }, 1400); }
}
function renderBag() {
  persist('oreyn-cart-v2', cart); const count = cart.reduce((sum, item) => sum + item.quantity, 0); const t = cartTotals();
  $('#bag-count').textContent = count; $('#drawer-count').textContent = `(${count})`; $('#checkout-button').disabled = count === 0;
  $('#shipping-progress').innerHTML = count ? `<div class="shipping-progress">${t.subtotal >= 120 ? 'Your preview includes complimentary delivery.' : `${money(120 - t.subtotal)} away from complimentary delivery in this preview.`}<div><i style="width:${Math.min(t.subtotal / 120 * 100, 100)}%"></i></div></div>` : '';
  $('#bag-items').innerHTML = cart.map((item, index) => { const p = products[item.id]; return `<div class="bag-row"><div class="bag-thumb ${item.id}">${item.id === 'discovery' ? 'ooo' : bottleMarkup(item.id, item.size)}</div><div><h3>${p.name}</h3><small>${sizeText(item.size)} / ${item.id === 'discovery' ? 'DISCOVERY SET' : 'EAU DE PARFUM'}</small><div class="quantity"><button data-quantity="${index}" data-delta="-1" aria-label="Remove one ${p.name}, ${sizeText(item.size)}">−</button><span>${item.quantity}</span><button data-quantity="${index}" data-delta="1" aria-label="Add one ${p.name}, ${sizeText(item.size)}" ${item.quantity >= 99 ? 'disabled' : ''}>+</button><button class="remove-item" data-remove="${index}" aria-label="Remove ${p.name}, ${sizeText(item.size)}, from bag">Remove</button></div></div><span class="price">${money(p.sizes[item.size] * item.quantity)}</span></div>`; }).join('') || '<div class="empty-state"><span class="star-mark">✳</span><h3>A little possibility.</h3><p>Your bag is waiting for its first feeling.</p><button class="pill dark" data-continue>Explore the collection <span>↗</span></button></div>';
  $('#bag-summary').innerHTML = count ? `<label class="gift-option"><input type="checkbox" id="gift-wrap" ${giftWrap ? 'checked' : ''}> Make it a gift <span style="margin-left:auto">+ €5</span></label><div class="summary-line"><span>Subtotal</span><span>${money(t.subtotal)}</span></div><div class="summary-line"><span>Delivery estimate</span><span>${t.shipping ? money(t.shipping) : 'Complimentary'}</span></div>${t.wrapping ? `<div class="summary-line"><span>Gift presentation</span><span>${money(t.wrapping)}</span></div>` : ''}<div class="summary-line total"><span>Estimated total</span><span>${money(t.total)}</span></div>` : '';
}
function continueShopping() { $$('dialog[open]').forEach(closeModal); $('#collection').scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }
function openCheckout() {
  if (!cart.length) return; const t = cartTotals();
  $('#checkout-content').innerHTML = `<p class="checkout-intro">A look at your next chapter. This is a concept-store preview: no order is placed, no payment is taken, and nothing is sent to a server.</p><div class="checkout-lines">${cart.map(item => `<div class="checkout-product"><div>${products[item.id].name}<small>${sizeText(item.size)} · Quantity ${item.quantity}</small></div><span>${money(products[item.id].sizes[item.size] * item.quantity)}</span></div>`).join('')}<div class="summary-line"><span>Delivery estimate</span><span>${t.shipping ? money(t.shipping) : 'Complimentary'}</span></div>${t.wrapping ? `<div class="summary-line"><span>Gift presentation</span><span>${money(t.wrapping)}</span></div>` : ''}<div class="summary-line total"><span>Preview total</span><span>${money(t.total)}</span></div></div><form class="checkout-form" id="preview-form"><label for="preview-name">Make this preview yours (optional first name)</label><input id="preview-name" placeholder="Your first name" autocomplete="off" maxlength="40"><button class="pill dark full-width" type="submit">Finish my preview <span>↗</span></button></form>`;
  openModal('#checkout-dialog');
  $('#preview-form').addEventListener('submit', event => { event.preventDefault(); const name = $('#preview-name').value.trim(); $('#checkout-content').innerHTML = '<div class="preview-success"><span class="star-mark">✳</span><h3 id="preview-title"></h3><p>Your preview is complete. Your chosen scents are still saved in your bag, ready for your next visit.</p><p>No order has been placed and no personal details have been saved.</p><button class="pill dark" data-continue>Back to your world <span>↗</span></button></div>'; $('#preview-title').textContent = name ? `A little more you, ${name}.` : 'A little more you.'; $('#preview-title').tabIndex = -1; $('#preview-title').focus(); });
}
const questions = [
  { title: 'What does your kind of day feel like?', choices: [['solar', 'Wide open.', 'Bright energy. Windows down. Anything could happen.'], ['after', 'A little unexpected.', 'Depth, intrigue, and a plan that changes.'], ['soft', 'Beautifully unhurried.', 'Quiet comforts. Room to breathe.']] },
  { title: 'Choose somewhere to disappear.', choices: [['soft', 'A sunlit room.', 'Linen sheets, a book, and no notifications.'], ['solar', 'A citrus grove.', 'Warm air, green leaves, and a glimpse of the sea.'], ['after', 'The city after midnight.', 'Low lights, good company, one more conversation.']] },
  { title: 'What would you like to leave behind?', choices: [['after', 'A little mystery.', 'An unexpected presence that stays in the memory.'], ['soft', 'A sense of closeness.', 'Something soft and quietly familiar.'], ['solar', 'A little light.', 'An easy warmth that brightens the room.']] }
];
let quizAnswers = [];
function renderQuiz() {
  const step = quizAnswers.length;
  if (step === questions.length) {
    const scores = { solar: 0, after: 0, soft: 0 }; quizAnswers.forEach(id => scores[id]++);
    const winner = Object.keys(scores).sort((a, b) => scores[b] - scores[a] || quizAnswers.lastIndexOf(b) - quizAnswers.lastIndexOf(a))[0]; const p = products[winner];
    $('#quiz-content').innerHTML = `<div class="quiz-result"><span class="eyebrow">YOUR INSTINCT LED YOU HERE</span><h2>${p.name}</h2><span class="detail-tagline">${p.tagline}</span><div class="result-art ${winner}">${bottleMarkup(winner)}</div><p>${p.description}</p><button class="pill dark" data-product="${winner}">Meet your match <span>↗</span></button><p class="small-note" style="margin-top:18px">A starting point based on your answers. Your skin gets the final say.</p><button class="quiz-back" data-quiz-restart>Follow a different feeling — start again</button></div>`;
  } else { const question = questions[step]; $('#quiz-content').innerHTML = `<div class="quiz-progress" aria-hidden="true">${questions.map((_, i) => `<i class="${i <= step ? 'done' : ''}"></i>`).join('')}</div><span class="quiz-step">QUESTION 0${step + 1} / 03</span><h2 tabindex="-1" id="quiz-question">${question.title}</h2>${question.choices.map(([id, title, description], i) => `<button class="quiz-option" data-quiz-answer="${id}"><span>0${i + 1}</span><div><b>${title}</b><small>${description}</small></div></button>`).join('')}${step ? '<button class="quiz-back" data-quiz-back>← Previous question</button>' : '<p class="small-note" style="margin-top:20px">There are no wrong answers. Go with the first feeling.</p>'}`; }
  if ($('#quiz-dialog').open) { const heading = $('#quiz-content h2'); heading.tabIndex = -1; heading.focus({ preventScroll: true }); $('#quiz-dialog').scrollTop = 0; }
}
function searchProducts() {
  const query = $('#search-input').value.trim().toLowerCase();
  const matches = Object.entries(products).filter(([, p]) => `${p.name} ${p.notes} ${p.keywords} ${p.top || ''} ${p.heart || ''} ${p.base || ''}`.toLowerCase().includes(query));
  $('#search-results').innerHTML = matches.map(([id, p]) => `<button class="search-result" ${id === 'discovery' ? 'data-discovery-link' : `data-product="${id}"`}><div class="${id}">${id === 'discovery' ? '<span style="font-size:30px">✳</span>' : bottleMarkup(id)}</div><div><strong>${p.name}</strong><small>${p.notes}</small></div><span>↗</span></button>`).join('') || '<p class="search-empty">No scent found just yet. Try a note like “iris” or a feeling like “warm”.</p>';
}
const articles = {
  ritual: { category: 'FIELD NOTES / THE EVERYDAY', title: 'The art of a small ritual.', intro: 'A good day does not always need a grand beginning. Sometimes it just needs a moment you can call your own.', body: [['Start before the noise.', 'Before the messages, before the list, there is a small space that belongs to you. Open a window. Notice the light. Let the room be exactly as it is for a minute. A ritual can be that simple: one familiar action, given your full attention.'], ['Choose one small thing.', 'The cup you reach for. The song you always come back to. A scent that marks the boundary between getting ready and being ready. Repetition gives ordinary things a shape. Over time, those things begin to feel like home.'], ['Let it change with you.', 'There is no perfect morning, and no single version of you to perform. Some days ask for energy. Others ask for softness. The point of a ritual is not to get it right; it is to check in. How do you feel? What would feel good next?'], ['Carry the moment.', 'Think of fragrance as a quiet punctuation mark. A way to say: here I am, and here begins the day. Not a transformation into somebody else. Just a little more attention to the person you already are.']] },
  notes: { category: 'FIELD NOTES / SCENT SCHOOL', title: 'A fragrance has a story arc.', intro: 'The first impression is only the opening line. Give a fragrance a little time to tell you the rest.', body: [['The opening.', 'Perfumers often talk about top, heart, and base notes as a way to describe a fragrance unfolding. The opening is the first impression: the brightness, the spark, the detail that asks you to lean in. In the Solar Drift concept, it is the imagined freshness of bergamot and mandarin.'], ['The heart.', 'As that first impression changes, other facets become easier to notice. This is often called the heart of the composition. It might feel floral, aromatic, spicy, or something that is harder to name. After Hours pairs the idea of black tea with powdery iris: two different textures in the same conversation.'], ['What stays.', 'The base gives a fragrance its sense of grounding. Woods, musks, and amber-like impressions can suggest warmth, closeness, or depth. Soft Static is built around the idea of a quiet trail: pear, ambrette, and pale woods that feel intimate rather than theatrical.'], ['A map, not a timetable.', 'A note pyramid is a useful way to imagine a composition, not a promise that every scent will develop in neat stages. Your surroundings and your own perception are part of the experience. The most useful question is simply: do I enjoy being here?']] },
  wardrobe: { category: 'FIELD NOTES / PERSONAL NOTES', title: 'Build a wardrobe of feelings.', intro: 'You have more than one favorite song. There is room for more than one favorite scent.', body: [['Begin with a feeling.', 'Instead of asking which fragrance you should wear, ask how you would like the day to feel. Bright and open? Warm and a little mysterious? Soft and close? A scent wardrobe starts with these small distinctions, not with rules about occasions or seasons.'], ['Make room for contrast.', 'Three fragrances can offer three very different perspectives. Solar Drift imagines light and movement. After Hours explores depth and texture. Soft Static stays close. The pleasure is in having a choice — and sometimes choosing the unexpected one.'], ['Live with a scent.', 'Give yourself time before deciding what belongs in your everyday. Revisit a fragrance on different days. Notice the moments when you reach for it without thinking. A favorite often reveals itself through the simple fact that you miss it when it is not there.'], ['Keep the rules yours.', 'A signature can be one fragrance, or it can be the instinct that connects several. There is no need for a collection to look like anybody else’s. The best wardrobe is the one that makes space for all your versions.']] }
};
const info = {
  shipping: { title: 'The finer details.', paragraphs: ['Oreyn is currently a concept store. Products, prices, delivery estimates, and gift presentation are shown to demonstrate the shopping experience. Orders and shipments are not available.', 'The bag preview uses €6 estimated delivery, waived at a merchandise subtotal of €120. Gift presentation adds €5. These are preview values, not live shipping terms.', 'Actual delivery regions, dispatch times, and return conditions will be published before the store begins accepting orders.'] },
  privacy: { title: 'Your space. Your privacy.', paragraphs: ['This concept site stores your bag and saved fragrances in your browser using localStorage so they can remain available when you return. You can remove individual items or clear the site’s browser data at any time.', 'Search and scent-finder answers stay in this page. The optional name in the order preview is not stored or sent to a server. The newsletter form does not transmit or save your email.', 'Google Fonts supplies the site’s typography and may receive standard connection information such as your IP address. No analytics or advertising scripts have been added.'] },
  terms: { title: 'A note on this experience.', paragraphs: ['Oreyn is an original perfume-store concept. The fragrance compositions, prices, product imagery, and editorial content illustrate a proposed brand experience.', 'Adding items to your bag or completing an order preview does not create an order or a contract. No payment details are requested and no payments are processed.', 'Final product specifications, ingredients, pricing, availability, and sale terms will need to be confirmed before a commercial launch.'] },
  contact: { title: 'Stay in our orbit.', paragraphs: ['The Oreyn world is taking shape. A dedicated customer-care address will be added when the store launches.', 'In the meantime, explore the collection, take the scent finder, or browse Field Notes. We hope you find a little moment that feels like you.'] }
};
function openArticle(id) { const a = articles[id]; if (!a) return; $('#editorial-content').innerHTML = `<span class="eyebrow">${a.category}</span><h2>${a.title}</h2><p class="article-intro">${a.intro}</p>${a.body.map(([title, text]) => `<h3>${title}</h3><p>${text}</p>`).join('')}<button class="pill dark" data-discovery-link>Explore a new feeling <span>↗</span></button>`; openModal('#editorial-dialog'); }
function openInfo(id) { const content = info[id]; if (!content) return; $('#editorial-content').innerHTML = `<span class="eyebrow">OREYN / THE DETAILS</span><h2>${content.title}</h2>${content.paragraphs.map(p => `<p>${p}</p>`).join('')}`; openModal('#editorial-dialog'); }
function setHero(id) { heroId = id; const p = products[id]; $('.hero').dataset.active = id; $('#hero-name').textContent = p.name; $('#hero-tagline').textContent = p.tagline; $('#hero-descriptor').textContent = `${p.number} / ${p.descriptor}`; $('#bottle-scent').textContent = p.name.toUpperCase(); $('#bottle-number').textContent = p.number; $('#hero-counter').textContent = `${p.number.slice(1)} — 03`; $$('[data-hero]').forEach(button => { const active = button.dataset.hero === id; button.classList.toggle('active', active); button.setAttribute('aria-pressed', active); }); }
function closeMenu() { $('#mobile-nav').hidden = true; $('#menu-toggle').setAttribute('aria-expanded', 'false'); $('#menu-toggle').setAttribute('aria-label', 'Open navigation'); }
document.addEventListener('click', async event => {
  const button = event.target.closest('button, a'); if (!button) return;
  if (button.hasAttribute('data-close')) closeModal(button.closest('dialog'));
  if (button.dataset.filter) { filter = button.dataset.filter; renderProducts(); }
  if (button.dataset.save) toggleSave(button.dataset.save);
  if (button.dataset.product) openProduct(button.dataset.product);
  if (button.dataset.add) addToCart(button.dataset.add, button.dataset.size);
  if (button.dataset.hero) setHero(button.dataset.hero);
  if (button.hasAttribute('data-open-quiz')) { quizAnswers = []; renderQuiz(); openModal('#quiz-dialog'); }
  if (button.hasAttribute('data-open-search')) { $('#search-input').value = ''; searchProducts(); openModal('#search-dialog'); $('#search-input').focus(); }
  if (button.dataset.detailSize) { detailSize = button.dataset.detailSize; $$('.size-options button').forEach(el => { const active = el.dataset.detailSize === detailSize; el.classList.toggle('active', active); el.setAttribute('aria-pressed', active); }); $('#product-detail .mini-volume').textContent = `EAU DE PARFUM / ${detailSize} ML`; $('#detail-add').dataset.size = detailSize; $('#detail-add').innerHTML = `Add to bag — ${money(products[detailId].sizes[detailSize])}<span>↗</span>`; }
  if (button.hasAttribute('data-quantity')) { const index = Number(button.dataset.quantity); const delta = Number(button.dataset.delta); if (cart[index]) { cart[index].quantity = Math.min(99, cart[index].quantity + delta); if (cart[index].quantity <= 0) cart.splice(index, 1); renderBag(); const next = $(`[data-quantity="${index}"][data-delta="${delta}"]:not(:disabled)`) || $('#continue-shopping'); next?.focus({ preventScroll: true }); } }
  if (button.hasAttribute('data-remove')) { cart.splice(Number(button.dataset.remove), 1); renderBag(); $('#continue-shopping').focus({ preventScroll: true }); }
  if (button.dataset.quizAnswer && quizAnswers.length < 3) { quizAnswers.push(button.dataset.quizAnswer); renderQuiz(); }
  if (button.hasAttribute('data-quiz-back')) { quizAnswers.pop(); renderQuiz(); }
  if (button.hasAttribute('data-quiz-restart')) { quizAnswers = []; renderQuiz(); }
  if (button.hasAttribute('data-continue')) continueShopping();
  if (button.hasAttribute('data-view-bag')) { renderBag(); openModal('#bag-dialog'); $('#toast').classList.remove('visible'); }
  if (button.hasAttribute('data-discovery-link')) { $$('dialog[open]').forEach(closeModal); location.hash = 'discovery'; }
  if (button.dataset.article) openArticle(button.dataset.article);
  if (button.dataset.info) openInfo(button.dataset.info);
  if (button.dataset.share) { const url = `${location.origin}${location.pathname}#scent/${button.dataset.share}`; try { await navigator.clipboard.writeText(url); button.textContent = 'Link copied ✓'; } catch { button.textContent = 'Use the scent URL in your address bar'; } }
  if (button.closest('#mobile-nav')) closeMenu();
});
document.addEventListener('change', event => { if (event.target.id === 'gift-wrap') { giftWrap = event.target.checked; renderBag(); $('#gift-wrap')?.focus(); } });
$('#open-bag').addEventListener('click', () => { renderBag(); openModal('#bag-dialog'); });
$('#continue-shopping').addEventListener('click', continueShopping);
$('#checkout-button').addEventListener('click', openCheckout);
$('#hero-details').addEventListener('click', () => openProduct(heroId));
$('#search-input').addEventListener('input', searchProducts);
$('#menu-toggle').addEventListener('click', () => { const opening = $('#mobile-nav').hidden; $('#mobile-nav').style.top = `${$('.site-header').getBoundingClientRect().bottom}px`; $('#mobile-nav').hidden = !opening; $('#menu-toggle').setAttribute('aria-expanded', String(opening)); $('#menu-toggle').setAttribute('aria-label', opening ? 'Close navigation' : 'Open navigation'); });
window.addEventListener('resize', closeMenu);
document.addEventListener('keydown', event => { if (event.key === 'Escape' && !$('#mobile-nav').hidden) { closeMenu(); $('#menu-toggle').focus(); } });
$('#newsletter-form').addEventListener('submit', event => { event.preventDefault(); $('#newsletter-status').textContent = 'Our list is not open yet. Your email has not been sent or saved — check back for the launch.'; $('#email').value = ''; });
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)');
window.oreynMotionPaused = reducedMotion.matches;
function updateMotion() { document.body.classList.toggle('motion-paused', window.oreynMotionPaused); $('#motion-toggle').setAttribute('aria-pressed', String(window.oreynMotionPaused)); $('#motion-label').textContent = window.oreynMotionPaused ? 'RESUME MOTION' : 'PAUSE MOTION'; window.dispatchEvent(new Event('oreyn-motion')); }
$('#motion-toggle').addEventListener('click', () => { window.oreynMotionPaused = !window.oreynMotionPaused; updateMotion(); });
reducedMotion.addEventListener('change', () => { window.oreynMotionPaused = reducedMotion.matches; updateMotion(); });
if ('IntersectionObserver' in window && !reducedMotion.matches) { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: .08 }); $$('.reveal').forEach(el => { el.classList.add('ready'); observer.observe(el); }); }
function handleRoute() { const match = location.hash.match(/^#scent\/(solar|after|soft)$/); if (match) openProduct(match[1], false); else if ($('#product-dialog').open) closeModal($('#product-dialog')); }
window.addEventListener('hashchange', handleRoute);
renderProducts(); renderBag(); updateMotion(); handleRoute();
